print("Listing of awesome superheros!")
print("******************************")
print("Batman")
print("Catwoman")
print("Captain Marvel")
print("Gerard")
print("Iron Man")
print("Looney the robot")
print("Moon Knight")
print("Robin")
print("Superman")
print("Spider Man")
print("The Punisher")
print("Wolverine")
print("Wonder Woman")
print("******************************")
