print("Listing of awesome superheros!")
print("Captain Marvel")
print("Spider Man")
print("THE PUNISHER")
print("Catwoman")
print("Batman")
print("Robin")
print("Superman")
print("Gerard")
print("Iron Man")
print("Wolverine")
print("WonderWoman")
print("Iron Man")
print("me as a cat")
print("Superman")
print("Wonder Woman")
print("Gerard")
